### ISSUE TITLE
Rename the package

### ISSUE THREAD

**Issue by chriscarrollsmith** [Teal-Insights/stdgeography#16]
- "r-" prefix
- Drop "std"?
- "economies" instead of "geographies"?

Suggested repository name: "r-economies"
Suggested package name: "economies"

**Comment by chriscarrollsmith** [comment]
Tagging @christophscheuch and @t-emery for feedback on the suggested name.

**Comment by chriscarrollsmith** [comment]
Claude suggestions:

econmap - Simple, indicates mapping functionality for economies
geoeconomy - Suggests geographic/economic relationships
econcode - Focuses on the coding/standardization aspect
econcodes - Similar to above, but plural to indicate multiple coding systems
geoconomics - A play on economics/geography, though might be too clever
econxref - Short for "economy cross-reference"
econkit - Suggests a toolkit for working with economy codes
econid - Short and focused on identification/standardization

**Comment by chriscarrollsmith** [comment]
Teal likes `econid`. Short, interpretable, doesn't seem derivative from `countrycodes` package.

**Comment by christophscheuch** [comment]
I also like econid because econ includes economies and more generally economics, so it may also include geographies, regions and institutions

**Comment by chriscarrollsmith** [comment]
> I also like econid because econ includes economies and more generally economics, so it may also include geographies, regions and institutions

Perfect! Thanks, Christoph!
